yarnPath: .yarn/releases/yarn-3.0.2.cjs
enableGlobalCache: true
npmRegistryServer: https://npm.pkg.github.com
packageExtensions:
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
